apiVersion: batch/v1
kind: Job
metadata:
    name: migration-job
spec:
    backoffLimit: 0
    template:
        metadata:
            labels:
                app: migration-job
        spec:
            restartPolicy: Never
            containers:
            -   name: migration-ctr
                image: devops4me/migrator:latest
                args: [ "do" ]
                volumeMounts:
                -   name: migrate-config
                    mountPath: /var/opt/migrator/configuration
                    readOnly: true
                -   name: spreadsheet-key
                    mountPath: /var/opt/migrator/data
                -   name: ssh-config-file
                    mountPath: /var/opt/migrator/.ssh/config
                    subPath: config
            volumes:
            -   name: migrate-config
                secret:
                    secretName: migration-config
            -   name: spreadsheet-key
                secret:
                    secretName: migration-sheetkey
                    items:
                    -   key: spreadsheet
                        path: team-repo-migration-data.xlsx
                    -   key: ssh-key
                        path: bitbucket-private-key.pem
            -   name: ssh-config-file
                secret:
                    secretName: migration-sshconfig
                    items:
                    -   key: sshconfigkey
                        path: config
