apiVersion: batch/v1
kind: Job
metadata:
    name: migration-job
spec:
    backoffLimit: 0
    template:
        metadata:
            labels:
                app: migration-job
        spec:
            restartPolicy: Never
            containers:
            -   name: migration-ctr
                image: devops4me/migrator
                volumeMounts:
                -   name: migrate-config
                    mountPath: /var/opt/migrator/configuration
                    readOnly: true
                -   name: repo-spreadsheet
                    mountPath: /var/opt/migrator/data
                    readOnly: true
                -   name: ssh-mount-files
                    mountPath: /var/opt/migrator/.ssh
            volumes:
            -   name: migrate-config
                secret:
                    secretName: migration-config
            -   name: repo-spreadsheet
                secret:
                    secretName: migration-spreadsheet
            -   name: ssh-mount-files
                secret:
                    secretName: migration-sshfiles
                    items:
                    -   key: ssh-config
                        path: config
                    -   key: ssh-key
                        path: bitbucket-private-key.pem
