apiVersion: batch/v1
kind: Job
metadata:
    name: migration-job
spec:
    backoffLimit: 0
    template:
        metadata:
            labels:
                app: migration-job
        spec:
            restartPolicy: Never
            containers:
            -   name: migration-ctr
                image: devops4me/migrator
                volumeMounts:
                -   name: migrate-config
                    mountPath: /var/opt/migrator/migrate-configuration.ini
                    readOnly: true
                -   name: repo-spreadsheet
                    mountPath: /var/opt/migrator/data/team-repo-migration-data.xlsx
                    readOnly: true
            volumes:
            -   name: migrate-config
                secret:
                    secretName: migration-config
            -   name: repo-spreadsheet
                secret:
                    secretName: migration-spreadsheet
